[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/rosary/"
  to = "/rosary"
  status = 301

[[redirects]]
  from = "/prayers/"
  to = "/prayers"
  status = 301

[[redirects]]
  from = "/prayers/:prayer/"
  to = "/prayers/:prayer"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
