const paragraphs = (...parts) => parts.join("\n\n");

export const commonPrayers = {
  signOfCross: {
    title: "Sign of the Cross",
    text: "In the name of the Father, and of the Son, and of the Holy Spirit. Amen.",
  },
  apostlesCreed: {
    title: "The Apostles' Creed",
    text: paragraphs(
      "I believe in God, the Father almighty, Creator of heaven and earth, and in Jesus Christ, his only Son, our Lord, who was conceived by the Holy Spirit, born of the Virgin Mary, suffered under Pontius Pilate, was crucified, died and was buried; he descended into hell; on the third day he rose again from the dead; he ascended into heaven, and is seated at the right hand of God the Father almighty; from there he will come to judge the living and the dead.",
      "I believe in the Holy Spirit, the holy catholic Church, the communion of saints, the forgiveness of sins, the resurrection of the body, and life everlasting. Amen.",
    ),
  },
  ourFather: {
    title: "Our Father",
    text: paragraphs(
      "Our Father, who art in heaven, hallowed be thy name; thy kingdom come; thy will be done on earth as it is in heaven.",
      "Give us this day our daily bread; and forgive us our trespasses as we forgive those who trespass against us; and lead us not into temptation, but deliver us from evil. Amen.",
    ),
  },
  hailMary: {
    title: "Hail Mary",
    text: paragraphs(
      "Hail Mary, full of grace, the Lord is with thee. Blessed art thou among women, and blessed is the fruit of thy womb, Jesus.",
      "Holy Mary, Mother of God, pray for us sinners, now and at the hour of our death. Amen.",
    ),
  },
  gloryBe: {
    title: "Glory Be",
    text: "Glory be to the Father, and to the Son, and to the Holy Spirit, as it was in the beginning, is now, and ever shall be, world without end. Amen.",
  },
  fatimaPrayer: {
    title: "Fatima Prayer",
    text: "O my Jesus, forgive us our sins, save us from the fires of hell; lead all souls to Heaven, especially those in most need of thy mercy. Amen.",
  },
  hailHolyQueen: {
    title: "Hail, Holy Queen",
    text: paragraphs(
      "Hail, Holy Queen, Mother of Mercy, our life, our sweetness, and our hope. To thee do we cry, poor banished children of Eve. To thee do we send up our sighs, mourning and weeping in this valley of tears.",
      "Turn then, most gracious advocate, thine eyes of mercy toward us, and after this our exile show unto us the blessed fruit of thy womb, Jesus. O clement, O loving, O sweet Virgin Mary.",
      "Pray for us, O holy Mother of God, that we may be made worthy of the promises of Christ.",
    ),
  },
  rosaryClosing: {
    title: "Closing Prayer",
    text: "O God, whose Only Begotten Son, by his life, death, and resurrection, has purchased for us the rewards of eternal life, grant, we beseech thee, that while meditating on these mysteries of the most holy Rosary of the Blessed Virgin Mary, we may imitate what they contain and obtain what they promise, through the same Christ our Lord. Amen.",
  },
};

export const prayers = [
  {
    id: "jesus-prayer",
    title: "The Jesus Prayer",
    shortTitle: "Jesus Prayer",
    subtitle: "A prayer of the heart",
    intro: "A simple prayer to repeat slowly, returning your attention to Christ with each breath.",
    text: "Lord Jesus Christ, Son of God, have mercy on me, a sinner.",
    note: "Pray it once with attention, or repeat it gently in rhythm with your breathing.",
  },
  {
    id: "our-father",
    title: "The Our Father",
    shortTitle: "Our Father",
    subtitle: "The prayer Jesus taught",
    intro: "The Lord's Prayer, given by Jesus to his disciples and prayed at the beginning of every Rosary decade.",
    text: commonPrayers.ourFather.text,
  },
  {
    id: "hail-mary",
    title: "The Hail Mary",
    shortTitle: "Hail Mary",
    subtitle: "A prayer with the Mother of God",
    intro: "A prayer drawn from Scripture that asks Mary to intercede for us and lead us closer to her Son.",
    text: commonPrayers.hailMary.text,
  },
  {
    id: "apostles-creed",
    title: "The Apostles' Creed",
    shortTitle: "Apostles' Creed",
    subtitle: "The faith we profess",
    intro: "An ancient summary of Christian belief and the opening profession of faith in the Rosary.",
    text: commonPrayers.apostlesCreed.text,
  },
  {
    id: "glory-be",
    title: "The Glory Be",
    shortTitle: "Glory Be",
    subtitle: "Praise of the Holy Trinity",
    intro: "A brief doxology giving glory to the Father, Son, and Holy Spirit.",
    text: commonPrayers.gloryBe.text,
  },
  {
    id: "act-of-contrition",
    title: "The Act of Contrition",
    shortTitle: "Act of Contrition",
    subtitle: "A prayer of repentance",
    intro: "A sincere return to God's mercy, with sorrow for sin and a desire to begin again.",
    text: paragraphs(
      "O my God, I am heartily sorry for having offended thee, and I detest all my sins because I dread the loss of heaven and the pains of hell, but most of all because they offend thee, my God, who art all good and deserving of all my love.",
      "I firmly resolve, with the help of thy grace, to confess my sins, to do penance, and to amend my life. Amen.",
    ),
  },
  {
    id: "morning-offering",
    title: "The Morning Offering",
    shortTitle: "Morning Offering",
    subtitle: "Begin the day with God",
    intro: "Offer the whole day, including its work, joys, and difficulties, to Jesus.",
    text: "O Jesus, through the Immaculate Heart of Mary, I offer you my prayers, works, joys, and sufferings of this day for all the intentions of your Sacred Heart, in union with the Holy Sacrifice of the Mass throughout the world, for the salvation of souls, the reparation of sins, the reunion of all Christians, and in particular for the intentions of the Holy Father this month. Amen.",
  },
  {
    id: "grace-before-meals",
    title: "Grace Before Meals",
    shortTitle: "Grace Before Meals",
    subtitle: "A blessing of gratitude",
    intro: "Give thanks for God's provision and ask his blessing upon the food you are about to receive.",
    text: "Bless us O Lord, and these thy gifts, which we are about to receive, from thy bounty, through Christ, our Lord. Amen.",
  },
  {
    id: "grace-after-meals",
    title: "Grace After Meals",
    shortTitle: "Grace After Meals",
    subtitle: "Thanksgiving after a meal",
    intro: "Thank God for his gifts and remember the faithful departed in prayer.",
    text: "We give thee thanks for all thy benefits, O Almighty God, who livest and reignest world without end. Amen. May the souls of the faithful departed, through the mercy of God, rest in peace. Amen.",
  },
  {
    id: "st-michael",
    title: "St. Michael the Archangel",
    shortTitle: "St. Michael",
    subtitle: "A prayer for protection",
    intro: "Ask the Prince of the heavenly host for defense against evil and strength in spiritual battle.",
    text: paragraphs(
      "St. Michael the Archangel, defend us in battle. Be our protection against the wickedness and snares of the devil. May God rebuke him, we humbly pray; and do thou, O Prince of the heavenly host, by the power of God, cast into hell Satan and all the evil spirits who prowl about the world seeking the ruin of souls.",
      "Amen.",
    ),
  },
  {
    id: "hail-holy-queen",
    title: "The Hail, Holy Queen",
    shortTitle: "Hail, Holy Queen",
    subtitle: "The concluding Rosary prayer",
    intro: "The traditional Marian prayer offered after the five decades of the Rosary.",
    text: commonPrayers.hailHolyQueen.text,
  },
];

export const featuredPrayerIds = [
  "jesus-prayer",
  "apostles-creed",
  "act-of-contrition",
  "morning-offering",
  "st-michael",
];

export const scriptureTranslation = "Douay–Rheims Bible";

export const scripturePassages = {
  "Luke 1:26-38": [
    [26, "And in the sixth month, the angel Gabriel was sent from God into a city of Galilee, called Nazareth,"],
    [27, "To a virgin espoused to a man whose name was Joseph, of the house of David; and the virgin’s name was Mary."],
    [28, "And the angel being come in, said unto her: Hail, full of grace, the Lord is with thee: blessed art thou among women."],
    [29, "Who having heard, was troubled at his saying, and thought with herself what manner of salutation this should be."],
    [30, "And the angel said to her: Fear not, Mary, for thou hast found grace with God."],
    [31, "Behold thou shalt conceive in thy womb, and shalt bring forth a son; and thou shalt call his name Jesus."],
    [32, "He shall be great, and shall be called the Son of the most High; and the Lord God shall give unto him the throne of David his father; and he shall reign in the house of Jacob for ever."],
    [33, "And of his kingdom there shall be no end."],
    [34, "And Mary said to the angel: How shall this be done, because I know not man?"],
    [35, "And the angel answering, said to her: The Holy Ghost shall come upon thee, and the power of the most High shall overshadow thee. And therefore also the Holy which shall be born of thee shall be called the Son of God."],
    [36, "And behold thy cousin Elizabeth, she also hath conceived a son in her old age; and this is the sixth month with her that is called barren:"],
    [37, "Because no word shall be impossible with God."],
    [38, "And Mary said: Behold the handmaid of the Lord; be it done to me according to thy word. And the angel departed from her."],
  ],
  "Luke 1:39-56": [
    [39, "And Mary rising up in those days, went into the hill country with haste into a city of Juda."],
    [40, "And she entered into the house of Zachary, and saluted Elizabeth."],
    [41, "And it came to pass, that when Elizabeth heard the salutation of Mary, the infant leaped in her womb. And Elizabeth was filled with the Holy Ghost:"],
    [42, "And she cried out with a loud voice, and said: Blessed art thou among women, and blessed is the fruit of thy womb."],
    [43, "And whence is this to me, that the mother of my Lord should come to me?"],
    [44, "For behold as soon as the voice of thy salutation sounded in my ears, the infant in my womb leaped for joy."],
    [45, "And blessed art thou that hast believed, because those things shall be accomplished that were spoken to thee by the Lord."],
    [46, "And Mary said: My soul doth magnify the Lord."],
    [47, "And my spirit hath rejoiced in God my Saviour."],
    [48, "Because he hath regarded the humility of his handmaid; for behold from henceforth all generations shall call me blessed."],
    [49, "Because he that is mighty, hath done great things to me; and holy is his name."],
    [50, "And his mercy is from generation unto generations, to them that fear him."],
    [51, "He hath shewed might in his arm: he hath scattered the proud in the conceit of their heart."],
    [52, "He hath put down the mighty from their seat, and hath exalted the humble."],
    [53, "He hath filled the hungry with good things; and the rich he hath sent empty away."],
    [54, "He hath received Israel his servant, being mindful of his mercy:"],
    [55, "As he spoke to our fathers, to Abraham and to his seed for ever."],
    [56, "And Mary abode with her about three months; and she returned to her own house."],
  ],
  "Luke 2:1-20": [
    [1, "And it came to pass, that in those days there went out a decree from Caesar Augustus, that the whole world should be enrolled."],
    [2, "This enrolling was first made by Cyrinus, the governor of Syria."],
    [3, "And all went to be enrolled, every one into his own city."],
    [4, "And Joseph also went up from Galilee, out of the city of Nazareth into Judea, to the city of David, which is called Bethlehem: because he was of the house and family of David,"],
    [5, "To be enrolled with Mary his espoused wife, who was with child."],
    [6, "And it came to pass, that when they were there, her days were accomplished, that she should be delivered."],
    [7, "And she brought forth her firstborn son, and wrapped him up in swaddling clothes, and laid him in a manger; because there was no room for them in the inn."],
    [8, "And there were in the same country shepherds watching, and keeping the night watches over their flock."],
    [9, "And behold an angel of the Lord stood by them, and the brightness of God shone round about them; and they feared with a great fear."],
    [10, "And the angel said to them: Fear not; for, behold, I bring you good tidings of great joy, that shall be to all the people:"],
    [11, "For, this day, is born to you a Saviour, who is Christ the Lord, in the city of David."],
    [12, "And this shall be a sign unto you. You shall find the infant wrapped in swaddling clothes, and laid in a manger."],
    [13, "And suddenly there was with the angel a multitude of the heavenly army, praising God, and saying:"],
    [14, "Glory to God in the highest; and on earth peace to men of good will."],
    [15, "And it came to pass, after the angels departed from them into heaven, the shepherds said one to another: Let us go over to Bethlehem, and let us see this word that is come to pass, which the Lord hath shewed to us."],
    [16, "And they came with haste; and they found Mary and Joseph, and the infant lying in the manger."],
    [17, "And seeing, they understood of the word that had been spoken to them concerning this child."],
    [18, "And all that heard, wondered; and at those things that were told them by the shepherds."],
    [19, "But Mary kept all these words, pondering them in her heart."],
    [20, "And the shepherds returned, glorifying and praising God, for all the things they had heard and seen, as it was told unto them."],
  ],
  "Luke 2:22-38": [
    [22, "And after the days of her purification, according to the law of Moses, were accomplished, they carried him to Jerusalem, to present him to the Lord:"],
    [23, "As it is written in the law of the Lord: Every male opening the womb shall be called holy to the Lord:"],
    [24, "And to offer a sacrifice, according as it is written in the law of the Lord, a pair of turtledoves, or two young pigeons:"],
    [25, "And behold there was a man in Jerusalem named Simeon, and this man was just and devout, waiting for the consolation of Israel; and the Holy Ghost was in him."],
    [26, "And he had received an answer from the Holy Ghost, that he should not see death, before he had seen the Christ of the Lord."],
    [27, "And he came by the Spirit into the temple. And when his parents brought in the child Jesus, to do for him according to the custom of the law,"],
    [28, "He also took him into his arms, and blessed God, and said:"],
    [29, "Now thou dost dismiss thy servant, O Lord, according to thy word in peace;"],
    [30, "Because my eyes have seen thy salvation,"],
    [31, "Which thou hast prepared before the face of all peoples:"],
    [32, "A light to the revelation of the Gentiles, and the glory of thy people Israel."],
    [33, "And his father and mother were wondering at those things which were spoken concerning him."],
    [34, "And Simeon blessed them, and said to Mary his mother: Behold this child is set for the fall, and for the resurrection of many in Israel, and for a sign which shall be contradicted;"],
    [35, "And thy own soul a sword shall pierce, that, out of many hearts, thoughts may be revealed."],
    [36, "And there was one Anna, a prophetess, the daughter of Phanuel, of the tribe of Aser; she was far advanced in years, and had lived with her husband seven years from her virginity."],
    [37, "And she was a widow until fourscore and four years; who departed not from the temple, by fastings and prayers serving night and day."],
    [38, "Now she, at the same hour, coming in, confessed to the Lord; and spoke of him to all that looked for the redemption of Israel."],
  ],
  "Luke 2:41-52": [
    [41, "And his parents went every year to Jerusalem, at the solemn day of the pasch,"],
    [42, "And when he was twelve years old, they going up into Jerusalem, according to the custom of the feast,"],
    [43, "And having fulfilled the days, when they returned, the child Jesus remained in Jerusalem; and his parents knew it not."],
    [44, "And thinking that he was in the company, they came a day’s journey, and sought him among their kinsfolks and acquaintance."],
    [45, "And not finding him, they returned into Jerusalem, seeking him."],
    [46, "And it came to pass, that, after three days, they found him in the temple, sitting in the midst of the doctors, hearing them, and asking them questions."],
    [47, "And all that heard him were astonished at his wisdom and his answers."],
    [48, "And seeing him, they wondered. And his mother said to him: Son, why hast thou done so to us? behold thy father and I have sought thee sorrowing."],
    [49, "And he said to them: How is it that you sought me? did you not know, that I must be about my father’s business?"],
    [50, "And they understood not the word that he spoke unto them."],
    [51, "And he went down with them, and came to Nazareth, and was subject to them. And his mother kept all these words in her heart."],
    [52, "And Jesus advanced in wisdom, and age, and grace with God and men."],
  ],
  "Matthew 3:13-17": [
    [13, "Then cometh Jesus from Galilee to the Jordan, unto John, to be baptized by him."],
    [14, "But John stayed him, saying: I ought to be baptized by thee, and comest thou to me?"],
    [15, "And Jesus answering, said to him: Suffer it to be so now. For so it becometh us to fulfill all justice. Then he suffered him."],
    [16, "And Jesus being baptized, forthwith came out of the water: and lo, the heavens were opened to him: and he saw the Spirit of God descending as a dove, and coming upon him."],
    [17, "And behold a voice from heaven, saying: This is my beloved Son, in whom I am well pleased."],
  ],
  "John 2:1-12": [
    [1, "And the third day, there was a marriage in Cana of Galilee: and the mother of Jesus was there."],
    [2, "And Jesus also was invited, and his disciples, to the marriage."],
    [3, "And the wine failing, the mother of Jesus saith to him: They have no wine."],
    [4, "And Jesus saith to her: Woman, what is that to me and to thee? my hour is not yet come."],
    [5, "His mother saith to the waiters: Whatsoever he shall say to you, do ye."],
    [6, "Now there were set there six waterpots of stone, according to the manner of the purifying of the Jews, containing two or three measures apiece."],
    [7, "Jesus saith to them: Fill the waterpots with water. And they filled them up to the brim."],
    [8, "And Jesus saith to them: Draw out now, and carry to the chief steward of the feast. And they carried it."],
    [9, "And when the chief steward had tasted the water made wine, and knew not whence it was, but the waiters knew who had drawn the water; the chief steward calleth the bridegroom,"],
    [10, "And saith to him: Every man at first setteth forth good wine, and when men have well drunk, then that which is worse. But thou hast kept the good wine until now."],
    [11, "This beginning of miracles did Jesus in Cana of Galilee; and manifested his glory, and his disciples believed in him."],
    [12, "After this he went down to Capharnaum, he and his mother, and his brethren, and his disciples: and they remained there not many days."],
  ],
  "Mark 1:14-15": [
    [14, "And after that John was delivered up, Jesus came into Galilee, preaching the gospel of the kingdom of God,"],
    [15, "And saying: The time is accomplished, and the kingdom of God is at hand: repent, and believe the gospel."],
  ],
  "Matthew 17:1-8": [
    [1, "And after six days Jesus taketh unto him Peter and James, and John his brother, and bringeth them up into a high mountain apart:"],
    [2, "And he was transfigured before them. And his face did shine as the sun: and his garments became white as snow."],
    [3, "And behold there appeared to them Moses and Elias talking with him."],
    [4, "And Peter answering, said to Jesus: Lord, it is good for us to be here: if thou wilt, let us make here three tabernacles, one for thee, and one for Moses, and one for Elias."],
    [5, "And as he was yet speaking, behold a bright cloud overshadowed them. And lo, a voice out of the cloud, saying: This is my beloved Son, in whom I am well pleased: hear ye him."],
    [6, "And the disciples hearing, fell upon their face, and were very much afraid."],
    [7, "And Jesus came and touched them: and said to them, Arise, and fear not."],
    [8, "And they lifting up their eyes saw no one but only Jesus."],
  ],
  "Luke 22:14-20": [
    [14, "And when the hour was come, he sat down, and the twelve apostles with him."],
    [15, "And he said to them: With desire I have desired to eat this pasch with you, before I suffer."],
    [16, "For I say to you, that from this time I will not eat it, till it be fulfilled in the kingdom of God."],
    [17, "And having taken the chalice, he gave thanks, and said: Take, and divide it among you:"],
    [18, "For I say to you, that I will not drink of the fruit of the vine, till the kingdom of God come."],
    [19, "And taking bread, he gave thanks, and brake; and gave to them, saying: This is my body, which is given for you. Do this for a commemoration of me."],
    [20, "In like manner the chalice also, after he had supped, saying: This is the chalice, the new testament in my blood, which shall be shed for you."],
  ],
  "Luke 22:39-46": [
    [39, "And going out, he went, according to his custom, to the mount of Olives. And his disciples also followed him."],
    [40, "And when he was come to the place, he said to them: Pray, lest ye enter into temptation."],
    [41, "And he was withdrawn away from them a stone’s cast; and kneeling down, he prayed,"],
    [42, "Saying: Father, if thou wilt, remove this chalice from me: but yet not my will, but thine be done."],
    [43, "And there appeared to him an angel from heaven, strengthening him. And being in an agony, he prayed the longer."],
    [44, "And his sweat became as drops of blood, trickling down upon the ground."],
    [45, "And when he rose up from prayer, and was come to his disciples, he found them sleeping for sorrow."],
    [46, "And he said to them: Why sleep you? arise, pray, lest you enter into temptation."],
  ],
  "John 19:1": [
    [1, "Then therefore, Pilate took Jesus, and scourged him."],
  ],
  "Matthew 27:27-31": [
    [27, "Then the soldiers of the governor taking Jesus into the hall, gathered together unto him the whole band;"],
    [28, "And stripping him, they put a scarlet cloak about him."],
    [29, "And platting a crown of thorns, they put it upon his head, and a reed in his right hand. And bowing the knee before him, they mocked him, saying: Hail, king of the Jews."],
    [30, "And spitting upon him, they took the reed, and struck his head."],
    [31, "And after they had mocked him, they took off the cloak from him, and put on him his own garments, and led him away to crucify him."],
  ],
  "Luke 23:26-32": [
    [26, "And as they led him away, they laid hold of one Simon of Cyrene, coming from the country; and they laid the cross on him to carry after Jesus."],
    [27, "And there followed him a great multitude of people, and of women, who bewailed and lamented him."],
    [28, "But Jesus turning to them, said: Daughters of Jerusalem, weep not over me; but weep for yourselves, and for your children."],
    [29, "For behold, the days shall come, wherein they will say: Blessed are the barren, and the wombs that have not borne, and the paps that have not given suck."],
    [30, "Then shall they begin to say to the mountains: Fall upon us; and to the hills: Cover us."],
    [31, "For if in the green wood they do these things, what shall be done in the dry?"],
    [32, "And there were also two other malefactors led with him to be put to death."],
  ],
  "John 19:17-37": [
    [17, "And bearing his own cross, he went forth to that place which is called Calvary, but in Hebrew Golgotha."],
    [18, "Where they crucified him, and with him two others, one on each side, and Jesus in the midst."],
    [19, "And Pilate wrote a title also, and he put it upon the cross. And the writing was: JESUS OF NAZARETH, THE KING OF THE JEWS."],
    [20, "This title therefore many of the Jews did read: because the place where Jesus was crucified was nigh to the city: and it was written in Hebrew, in Greek, and in Latin."],
    [21, "Then the chief priests of the Jews said to Pilate: Write not, The King of the Jews; but that he said, I am the King of the Jews."],
    [22, "Pilate answered: What I have written, I have written."],
    [23, "The soldiers therefore, when they had crucified him, took his garments, (and they made four parts, to every soldier a part,) and also his coat. Now the coat was without seam, woven from the top throughout."],
    [24, "They said then one to another: Let us not cut it, but let us cast lots for it, whose it shall be; that the scripture might be fulfilled, saying: They have parted my garments among them, and upon my vesture they have cast lot. And the soldiers indeed did these things."],
    [25, "Now there stood by the cross of Jesus, his mother, and his mother’s sister, Mary of Cleophas, and Mary Magdalen."],
    [26, "When Jesus therefore had seen his mother and the disciple standing whom he loved, he saith to his mother: Woman, behold thy son."],
    [27, "After that, he saith to the disciple: Behold thy mother. And from that hour, the disciple took her to his own."],
    [28, "Afterwards, Jesus knowing that all things were now accomplished, that the scripture might be fulfilled, said: I thirst."],
    [29, "Now there was a vessel set there full of vinegar. And they, putting a sponge full of vinegar and hyssop, put it to his mouth."],
    [30, "Jesus therefore, when he had taken the vinegar, said: It is consummated. And bowing his head, he gave up the ghost."],
    [31, "Then the Jews, (because it was the parasceve,) that the bodies might not remain on the cross on the sabbath day, (for that was a great sabbath day,) besought Pilate that their legs might be broken, and that they might be taken away."],
    [32, "The soldiers therefore came; and they broke the legs of the first, and of the other that was crucified with him."],
    [33, "But after they were come to Jesus, when they saw that he was already dead, they did not break his legs."],
    [34, "But one of the soldiers with a spear opened his side, and immediately there came out blood and water."],
    [35, "And he that saw it, hath given testimony, and his testimony is true. And he knoweth that he saith true; that you also may believe."],
    [36, "For these things were done, that the scripture might be fulfilled: You shall not break a bone of him."],
    [37, "And again another scripture saith: They shall look on him whom they pierced."],
  ],
  "Matthew 28:1-10": [
    [1, "And in the end of the sabbath, when it began to dawn towards the first day of the week, came Mary Magdalen and the other Mary, to see the sepulchre."],
    [2, "And behold there was a great earthquake. For an angel of the Lord descended from heaven, and coming, rolled back the stone, and sat upon it."],
    [3, "And his countenance was as lightning, and his raiment as snow."],
    [4, "And for fear of him, the guards were struck with terror, and became as dead men."],
    [5, "And the angel answering, said to the women: Fear not you; for I know that you seek Jesus who was crucified."],
    [6, "He is not here, for he is risen, as he said. Come, and see the place where the Lord was laid."],
    [7, "And going quickly, tell ye his disciples that he is risen: and behold he will go before you into Galilee; there you shall see him. Lo, I have foretold it to you."],
    [8, "And they went out quickly from the sepulchre with fear and great joy, running to tell his disciples."],
    [9, "And behold Jesus met them, saying: All hail. But they came up and took hold of his feet, and adored him."],
    [10, "Then Jesus said to them: Fear not. Go, tell my brethren that they go into Galilee, there they shall see me."],
  ],
  "Acts 1:6-11": [
    [6, "They therefore who were come together, asked him, saying: Lord, wilt thou at this time restore again the kingdom to Israel?"],
    [7, "But he said to them: It is not for you to know the times or moments, which the Father hath put in his own power:"],
    [8, "But you shall receive the power of the Holy Ghost coming upon you, and you shall be witnesses unto me in Jerusalem, and in all Judea, and Samaria, and even to the uttermost part of the earth."],
    [9, "And when he had said these things, while they looked on, he was raised up: and a cloud received him out of their sight."],
    [10, "And while they were beholding him going up to heaven, behold two men stood by them in white garments."],
    [11, "Who also said: Ye men of Galilee, why stand you looking up to heaven? This Jesus who is taken up from you into heaven, shall so come, as you have seen him going into heaven."],
  ],
  "Acts 2:1-13": [
    [1, "And when the days of the Pentecost were accomplished, they were all together in one place:"],
    [2, "And suddenly there came a sound from heaven, as of a mighty wind coming, and it filled the whole house where they were sitting."],
    [3, "And there appeared to them parted tongues as it were of fire, and it sat upon every one of them:"],
    [4, "And they were all filled with the Holy Ghost, and they began to speak with divers tongues, according as the Holy Ghost gave them to speak."],
    [5, "Now there were dwelling at Jerusalem, Jews, devout men, out of every nation under heaven."],
    [6, "And when this was noised abroad, the multitude came together, and were confounded in mind, because that every man heard them speak in his own tongue."],
    [7, "And they were all amazed, and wondered, saying: Behold, are not all these, that speak, Galileans?"],
    [8, "And how have we heard, every man our own tongue wherein we were born?"],
    [9, "Parthians, and Medes, and Elamites, and inhabitants of Mesopotamia, Judea, and Cappadocia, Pontus and Asia,"],
    [10, "Phrygia, and Pamphylia, Egypt, and the parts of Libya about Cyrene, and strangers of Rome,"],
    [11, "Jews also, and proselytes, Cretes, and Arabians: we have heard them speak in our own tongues the wonderful works of God."],
    [12, "And they were all astonished, and wondered, saying one to another: What meaneth this?"],
    [13, "But others mocking, said: These men are full of new wine."],
  ],
  "Revelation 12:1": [
    [1, "And a great sign appeared in heaven: A woman clothed with the sun, and the moon under her feet, and on her head a crown of twelve stars:"],
  ],
};

export const mysteries = {
  joyful: {
    name: "Joyful Mysteries",
    days: "Monday and Saturday",
    theme: "The hidden life of Christ",
    color: "gold",
    items: [
      {
        title: "The Annunciation",
        image: "/assets/mysteries/joyful-annunciation.webp",
        scripture: "Luke 1:26-38",
        fruit: "Humility",
        meditation: "Mary receives the angel's word with faith and gives herself freely to God's will.",
      },
      {
        title: "The Visitation",
        image: "/assets/mysteries/joyful-visitation.webp",
        scripture: "Luke 1:39-56",
        fruit: "Love of neighbor",
        meditation: "Carrying Christ within her, Mary goes in haste to serve Elizabeth.",
      },
      {
        title: "The Nativity",
        image: "/assets/mysteries/joyful-nativity.webp",
        scripture: "Luke 2:1-20",
        fruit: "Poverty of spirit",
        meditation: "The Son of God enters the world in humility and is laid in a manger.",
      },
      {
        title: "The Presentation",
        image: "/assets/mysteries/joyful-presentation.webp",
        scripture: "Luke 2:22-38",
        fruit: "Obedience",
        meditation: "Mary and Joseph present Jesus to the Father, and Simeon recognizes the promised light.",
      },
      {
        title: "The Finding in the Temple",
        image: "/assets/mysteries/joyful-finding-temple.webp",
        scripture: "Luke 2:41-52",
        fruit: "Desire for Jesus",
        meditation: "After three days of searching, Mary and Joseph find Jesus in his Father's house.",
      },
    ],
  },
  luminous: {
    name: "Luminous Mysteries",
    days: "Thursday",
    theme: "The public ministry of Christ",
    color: "blue",
    items: [
      {
        title: "The Baptism in the Jordan",
        image: "/assets/mysteries/luminous-baptism-jordan.webp",
        scripture: "Matthew 3:13-17",
        fruit: "Openness to the Holy Spirit",
        meditation: "The Father's voice reveals Jesus as the beloved Son, and the Spirit descends upon him.",
      },
      {
        title: "The Wedding at Cana",
        image: "/assets/mysteries/luminous-wedding-cana.webp",
        scripture: "John 2:1-12",
        fruit: "Trust in Mary's intercession",
        meditation: "At Mary's request, Jesus performs his first sign and reveals his glory.",
      },
      {
        title: "The Proclamation of the Kingdom",
        image: "/assets/mysteries/luminous-proclamation-kingdom.webp",
        scripture: "Mark 1:14-15",
        fruit: "Conversion",
        meditation: "Jesus calls every heart to repentance, mercy, and the life of the Kingdom.",
      },
      {
        title: "The Transfiguration",
        image: "/assets/mysteries/luminous-transfiguration.webp",
        scripture: "Matthew 17:1-8",
        fruit: "Desire for holiness",
        meditation: "The glory of Christ shines before the disciples, strengthening them for what lies ahead.",
      },
      {
        title: "The Institution of the Eucharist",
        image: "/assets/mysteries/luminous-eucharist.webp",
        scripture: "Luke 22:14-20",
        fruit: "Adoration",
        meditation: "Jesus gives himself as food and establishes the memorial of his saving sacrifice.",
      },
    ],
  },
  sorrowful: {
    name: "Sorrowful Mysteries",
    days: "Tuesday and Friday",
    theme: "The Passion of Christ",
    color: "red",
    items: [
      {
        title: "The Agony in the Garden",
        image: "/assets/mysteries/sorrowful-agony-garden.webp",
        scripture: "Luke 22:39-46",
        fruit: "Surrender to God's will",
        meditation: "In anguish, Jesus prays and freely accepts the Father's will for our salvation.",
      },
      {
        title: "The Scourging at the Pillar",
        image: "/assets/mysteries/sorrowful-scourging-pillar.webp",
        scripture: "John 19:1",
        fruit: "Purity",
        meditation: "Jesus endures cruel suffering in silence, bearing the wounds of human sin.",
      },
      {
        title: "The Crowning with Thorns",
        image: "/assets/mysteries/sorrowful-crowning-thorns.webp",
        scripture: "Matthew 27:27-31",
        fruit: "Moral courage",
        meditation: "Mocked as a king, Christ answers humiliation with patience and love.",
      },
      {
        title: "The Carrying of the Cross",
        image: "/assets/mysteries/sorrowful-carrying-cross.webp",
        scripture: "Luke 23:26-32",
        fruit: "Patience in trials",
        meditation: "Jesus carries the cross to Calvary and invites us to follow him faithfully.",
      },
      {
        title: "The Crucifixion",
        image: "/assets/mysteries/sorrowful-crucifixion.webp",
        scripture: "John 19:17-37",
        fruit: "Self-giving love",
        meditation: "From the cross, Jesus forgives, entrusts Mary to us, and gives his life for the world.",
      },
    ],
  },
  glorious: {
    name: "Glorious Mysteries",
    days: "Wednesday and Sunday",
    theme: "The triumph of Christ",
    color: "green",
    items: [
      {
        title: "The Resurrection",
        image: "/assets/mysteries/glorious-resurrection.webp",
        scripture: "Matthew 28:1-10",
        fruit: "Faith",
        meditation: "Christ rises from the dead, conquering sin and opening the way to eternal life.",
      },
      {
        title: "The Ascension",
        image: "/assets/mysteries/glorious-ascension.webp",
        scripture: "Acts 1:6-11",
        fruit: "Hope",
        meditation: "Jesus returns to the Father and sends his disciples to witness to the Gospel.",
      },
      {
        title: "The Descent of the Holy Spirit",
        image: "/assets/mysteries/glorious-pentecost.webp",
        scripture: "Acts 2:1-13",
        fruit: "Wisdom",
        meditation: "The Holy Spirit fills Mary and the apostles with courage to proclaim Christ.",
      },
      {
        title: "The Assumption of Mary",
        image: "/assets/mysteries/glorious-assumption.webp",
        scripture: "Revelation 12:1",
        fruit: "Grace of a holy death",
        meditation: "Mary is taken body and soul into heavenly glory, a sign of hope for the Church.",
      },
      {
        title: "The Coronation of Mary",
        image: "/assets/mysteries/glorious-coronation.webp",
        scripture: "Revelation 12:1",
        fruit: "Trust in Mary's intercession",
        meditation: "Mary is crowned Queen of Heaven and continues to pray for all her children.",
      },
    ],
  },
};

export function getSuggestedMystery(date = new Date()) {
  return ["glorious", "joyful", "sorrowful", "glorious", "luminous", "sorrowful", "joyful"][
    date.getDay()
  ];
}
